//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataAccess
{
    using System;
    using System.Collections.Generic;

    // This class echos the table structure in database. The column names and there types is same as that of table. Used EntityFramework to auto generate this model based on the [dbo].[MovieTicket] table.
    public partial class MovieTicket
    {
        public int TicketId { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string MovieName { get; set; }
        public bool isExpired { get; set; }
    }
}
